spring.application.name=Placementmanagement

spring.datasource.url=jdbc:postgresql://localhost:5432/placement_management
spring.datasource.username=postgres
spring.datasource.password=Postgres@123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081